/*
 * Generated by scripts/sync-channels.mjs from the "agentcomms" field of each channel's package.json.
 * Run `pnpm sync:channels` after changing one; do not edit this file.
 */
import type { ChannelEntry } from './channel-manifest.ts';

/** The channels built into this release, by their word: a channel is a string, and these are the known ones. */
export type BuiltInChannel = 'core' | 'gmail' | 'slack';

/** Every first-party channel, the core first: what core knows about each without installing it. */
export const CHANNEL_SNAPSHOT: readonly ChannelEntry[] = [
  {
    packageName: '@agentcomms/core',
    manifest: {
      contract: 1,
      channel: 'core',
      label: 'agentcomms (core)',
      binary: 'agentcomms',
      server: {
        defaultName: 'agentcomms',
        npxPackage: '@agentcomms/core',
        npxArgs: ['mcp'],
      },
      approve: 'agentcomms approve',
      skills: {
        prefix: 'comms-',
        contract: 'skills/_shared/contract-comms.md',
      },
    },
  },
  {
    packageName: '@agentcomms/gmail',
    manifest: {
      contract: 1,
      channel: 'gmail',
      label: 'Gmail',
      binary: 'agent-gmail',
      server: {
        defaultName: 'gmail',
        npxPackage: '@agentcomms/gmail-mcp',
        entryFiles: [['node_modules', '@agentcomms', 'gmail-mcp', 'dist', 'server.mjs']],
        bins: ['agent-gmail-mcp'],
      },
      accounts: {
        map: 'inboxes',
        noun: 'mailbox',
        modes: ['read', 'send'],
        guarantee: {
          ceiling: 'grant',
          floor: 'grant',
          why: 'A mailbox connected at the read tier holds only gmail.readonly, which Google will not send with. Every tier that can draft can also send, so above read it is the approval gate, not the grant, that stands between a draft and a sent message.',
        },
      },
      narrowing: [
        {
          option: 'inbox',
          flag: '--inbox',
          kind: 'pin',
        },
        {
          option: 'readOnly',
          flag: '--read-only',
          kind: 'switch',
        },
      ],
      rivals: {
        packages: [
          {
            name: '@artymclabin/gmail-mcp',
          },
          {
            name: '@gongrzhe/server-gmail-autoauth-mcp',
            unscoped: true,
          },
          {
            name: '@shinzolabs/gmail-mcp',
          },
        ],
      },
      hosts: ['accounts.google.com', 'oauth2.googleapis.com', 'gmail.googleapis.com', 'people.googleapis.com'],
      approve: 'agent-gmail approve',
      skills: {
        prefix: 'gmail-',
        contract: 'skills/_shared/contract-gmail.md',
      },
    },
  },
  {
    packageName: '@agentcomms/slack',
    manifest: {
      contract: 1,
      channel: 'slack',
      label: 'Slack',
      binary: 'agent-slack',
      server: {
        defaultName: 'slack',
        npxPackage: '@agentcomms/slack',
        npxArgs: ['mcp'],
      },
      accounts: {
        map: 'accounts',
        noun: 'workspace',
        modes: ['read', 'send'],
        guarantee: {
          ceiling: 'grant',
          floor: 'grant',
          why: 'A workspace connected to read holds a user token with no posting scope, so Slack itself refuses to post with it; one connected to send holds the scopes its app declares and no more.',
        },
      },
      narrowing: [
        {
          option: 'workspace',
          flag: '--workspace',
          kind: 'pin',
        },
      ],
      rivals: {
        word: 'slack',
        can: 'post to Slack',
      },
      hosts: ['slack.com'],
      approve: 'agent-slack approve',
      skills: {
        prefix: 'slack-',
        contract: 'skills/_shared/contract-slack.md',
      },
    },
  },
];
